In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('train_set.csv')

C:\Users\obinn\AppData\Local\Temp\ipykernel_39972\662679527.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('train_set.csv')


In [3]:
data

X_STATE  IMONTH  IYEAR  DISPCODE  PVTRESD1 COLGHOUS  LADULT1  CTELNUM1  \
0           29      11   2021      1100       NaN      NaN      NaN       1.0   
1           28       3   2021      1100       NaN      NaN      NaN       1.0   
2           19       8   2021      1100       NaN      NaN      NaN       1.0   
3           27       9   2021      1100       NaN      NaN      NaN       1.0   
4           50       4   2021      1100       NaN      NaN      NaN       1.0   
...        ...     ...    ...       ...       ...      ...      ...       ...   
65797       49       7   2021      1100       NaN      NaN      NaN       1.0   
65798        8      10   2021      1100       NaN      NaN      NaN       1.0   
65799       50       7   2021      1100       NaN      NaN      NaN       1.0   
65800       18       6   2021      1100       NaN      NaN      NaN       1.0   
65801       31       7   2021      1100       NaN      NaN      NaN       1.0   

       CADULT1  PVTRESD3  ...  X_AIDTST4  FTJUDA2_  FRUTDA2_  GRENDA1_  \
0          1.0       1.0  ...        9.0       NaN      14.0     100.0   
1          1.0       1.0  ...        1.0       0.0     200.0      33.0   
2          1.0       1.0  ...        2.0       0.0      43.0       3.0   
3          1.0       1.0  ...        1.0       3.0       7.0      29.0   
4          1.0       1.0  ...        1.0     200.0     500.0     300.0   
...        ...       ...  ...        ...       ...       ...       ...   
65797      1.0       1.0  ...        2.0       7.0     300.0      14.0   
65798      1.0       1.0  ...        1.0       3.0      10.0      13.0   
65799      1.0       1.0  ...        2.0      13.0     200.0     100.0   
65800      1.0       1.0  ...        1.0     100.0      43.0      14.0   
65801      1.0       1.0  ...        2.0      29.0      57.0      14.0   

       FRNCHDA_  POTADA1_  VEGEDA2_  X_FRUTSU1  X_VEGESU1  Outcome  
0           0.0       0.0     100.0        NaN      200.0      Neg  
1          10.0      17.0     100.0      200.0      160.0      Pos  
2           7.0       2.0      14.0       43.0       26.0      Neg  
3         100.0     100.0      50.0       10.0      279.0      Pos  
4         100.0     500.0     600.0      700.0     1500.0      Pos  
...         ...       ...       ...        ...        ...      ...  
65797      14.0      43.0     300.0      307.0      371.0      Neg  
65798       7.0       3.0      83.0       13.0      106.0      Neg  
65799      14.0      29.0     100.0      213.0      243.0      Neg  
65800      57.0      14.0     100.0      143.0      185.0      Neg  
65801      57.0      14.0     100.0       86.0      185.0      Neg  

[65802 rows x 128 columns]

In [4]:
data.shape

(65802, 128)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65802 entries, 0 to 65801
Columns: 128 entries, X_STATE to Outcome
dtypes: float64(78), int64(48), object(2)
memory usage: 64.3+ MB


# DATA CLEANING 

### Change the headers to lowercase

In [6]:
data.columns = data.columns.str.lower()

In [7]:
data

x_state  imonth  iyear  dispcode  pvtresd1 colghous  ladult1  ctelnum1  \
0           29      11   2021      1100       NaN      NaN      NaN       1.0   
1           28       3   2021      1100       NaN      NaN      NaN       1.0   
2           19       8   2021      1100       NaN      NaN      NaN       1.0   
3           27       9   2021      1100       NaN      NaN      NaN       1.0   
4           50       4   2021      1100       NaN      NaN      NaN       1.0   
...        ...     ...    ...       ...       ...      ...      ...       ...   
65797       49       7   2021      1100       NaN      NaN      NaN       1.0   
65798        8      10   2021      1100       NaN      NaN      NaN       1.0   
65799       50       7   2021      1100       NaN      NaN      NaN       1.0   
65800       18       6   2021      1100       NaN      NaN      NaN       1.0   
65801       31       7   2021      1100       NaN      NaN      NaN       1.0   

       cadult1  pvtresd3  ...  x_aidtst4  ftjuda2_  frutda2_  grenda1_  \
0          1.0       1.0  ...        9.0       NaN      14.0     100.0   
1          1.0       1.0  ...        1.0       0.0     200.0      33.0   
2          1.0       1.0  ...        2.0       0.0      43.0       3.0   
3          1.0       1.0  ...        1.0       3.0       7.0      29.0   
4          1.0       1.0  ...        1.0     200.0     500.0     300.0   
...        ...       ...  ...        ...       ...       ...       ...   
65797      1.0       1.0  ...        2.0       7.0     300.0      14.0   
65798      1.0       1.0  ...        1.0       3.0      10.0      13.0   
65799      1.0       1.0  ...        2.0      13.0     200.0     100.0   
65800      1.0       1.0  ...        1.0     100.0      43.0      14.0   
65801      1.0       1.0  ...        2.0      29.0      57.0      14.0   

       frnchda_  potada1_  vegeda2_  x_frutsu1  x_vegesu1  outcome  
0           0.0       0.0     100.0        NaN      200.0      Neg  
1          10.0      17.0     100.0      200.0      160.0      Pos  
2           7.0       2.0      14.0       43.0       26.0      Neg  
3         100.0     100.0      50.0       10.0      279.0      Pos  
4         100.0     500.0     600.0      700.0     1500.0      Pos  
...         ...       ...       ...        ...        ...      ...  
65797      14.0      43.0     300.0      307.0      371.0      Neg  
65798       7.0       3.0      83.0       13.0      106.0      Neg  
65799      14.0      29.0     100.0      213.0      243.0      Neg  
65800      57.0      14.0     100.0      143.0      185.0      Neg  
65801      57.0      14.0     100.0       86.0      185.0      Neg  

[65802 rows x 128 columns]

### Drop missing values by columnwise (Condition: 70% headers with null values)

In [8]:
# This command shows the columns with missing values in descending order

data.isnull().sum().sort_values(ascending=False).head(40)

toldcfs     65802
colghous    65798
havehepc    65768
cclghous    65651
psatest1    65472
vircolo1    65469
stooldn1    65469
smalstol    65469
csrvdein    65073
csrvdoc1    65073
csrvinsr    65073
crvclpap    64824
crvclhpv    64819
colnsigm    64714
csrvtrt3    64565
cncrage     64127
cncrtyp1    64127
cncrdiff    64099
hadhyst2    64063
cervscrn    64045
hadmam      64045
havehepb    63999
shingle2    63636
hpvadvc4    63468
tetanus1    63410
rsnmrjn2    62779
firearm5    60437
lcsctscn    60428
cimemlos    60243
wtchsalt    59358
aceadsaf    55718
acedivrc    55718
acedrink    55718
aceadned    55718
aceprisn    55718
acedrugs    55718
acepunch    55718
acehurt1    55718
aceswear    55718
acetouch    55718
dtype: int64

In [9]:
# This command drops the column with missing values greater or equal to 56000

data.dropna(thresh=56000, inplace=True, axis=1)

In [10]:
# The .shape attribute shows the structure of the new table after dropping the 'NaN' columns

data.shape

(65802, 68)

### Check and drop duplicates if any

In [11]:
data.duplicated().sum()

0

### Data Imputation for Missing values

In [12]:
# Recheck for null values columns

In [13]:
# The statement shows the remaining columns with missing values (less than 70%)

data.isnull().sum().sort_values(ascending=False).head(20)

x_rfchol3    8807
toldhi3      8761
x_bmi5cat    4387
x_vegesu1    2972
x_frutsu1    2201
frutda2_     1364
potada1_     1342
ftjuda2_     1200
vegeda2_     1164
grenda1_     1059
x_urbstat    1032
x_metstat    1032
frnchda_      944
x_michd       746
x_drdxar3     414
x_lmtwrk3     414
x_lmtact3     414
x_aidtst4       1
medcost1        1
x_cholch3       0
dtype: int64

### Column 1.

In [14]:
# Count the frequency of the non-null values in the column

data['x_rfchol3'].value_counts()

1.0    31774
2.0    24741
9.0      480
Name: x_rfchol3, dtype: int64

In [15]:
# The command fills the 'NaN' cells with the highest frequency value.

data['x_rfchol3'].fillna(1, inplace=True)

In [16]:


data['x_rfchol3'].isnull().sum()

0

### For Column 2.

In [17]:
# Same process repeated for this column

data['toldhi3'].unique()

array([ 1.,  2., nan,  7.,  9.])

In [18]:
data['toldhi3'].value_counts()

2.0    31819
1.0    24742
7.0      434
9.0       46
Name: toldhi3, dtype: int64

In [19]:
data['toldhi3'].fillna(2, inplace=True)

In [20]:
data['toldhi3'].isnull().sum()

0

### Column 3

In [21]:
data['x_bmi5cat'].unique()

array([ 4.,  3.,  1.,  2., nan])

In [22]:
data['x_bmi5cat'].value_counts()

4.0    23041
3.0    20362
2.0    16965
1.0     1047
Name: x_bmi5cat, dtype: int64

In [23]:
data['x_bmi5cat'].fillna(4.0, inplace=True)

### Column 4

In [24]:
data['x_vegesu1'].unique()

array([  200.,   160.,    26., ..., 10207., 11502.,   791.])

In [25]:
data['x_vegesu1'].value_counts().head(20)

200.0    1441
157.0    1351
143.0    1092
186.0     986
100.0     984
214.0     954
243.0     866
171.0     849
114.0     826
172.0     772
228.0     755
129.0     731
86.0      692
128.0     662
150.0     620
142.0     604
257.0     584
300.0     564
229.0     558
217.0     501
Name: x_vegesu1, dtype: int64

#### Obtain the statistics of the column

In [26]:
data['x_vegesu1'].describe()

count    62830.000000
mean       264.306653
std       1008.580317
min          0.000000
25%        113.000000
50%        163.000000
75%        229.000000
max      31114.000000
Name: x_vegesu1, dtype: float64

In [27]:
import math

In [28]:
# Fill the missing values with the median since the Q3 value is still less than the mean value

data['x_vegesu1'].fillna(math.ceil(data['x_vegesu1'].median()), inplace=True)

In [29]:
data['x_vegesu1'].isnull().sum()

0

### Column 5

In [30]:
data['x_frutsu1'].fillna(math.ceil(data['x_vegesu1'].mean()), inplace=True)

### Column 6

In [31]:
data['frutda2_'].value_counts().sort_values(ascending=False)

100.0     18693
200.0      9380
43.0       5936
29.0       4485
57.0       3481
          ...  
1329.0        1
9200.0        1
183.0         1
217.0         1
120.0         1
Name: frutda2_, Length: 97, dtype: int64

### Checking the descrptive statistics of the columns for Outlier detection

In [32]:
data['frutda2_'].describe()

count    64438.000000
mean       128.386573
std        476.877974
min          0.000000
25%         33.000000
50%        100.000000
75%        100.000000
max       9900.000000
Name: frutda2_, dtype: float64

In [33]:
data['frutda2_'].fillna(math.ceil(data['x_vegesu1'].median()), inplace=True)

In [34]:
data['frutda2_'].isnull().sum()

0

### Column 7

In [35]:
data['potada1_'].describe()

count    64460.000000
mean        27.999271
std        174.626928
min          0.000000
25%          7.000000
50%         14.000000
75%         29.000000
max       9900.000000
Name: potada1_, dtype: float64

In [36]:
data['potada1_'].fillna(math.ceil(data['potada1_'].median()), inplace=True)

### Column 8


In [37]:
data['ftjuda2_'].describe()

count    64602.000000
mean        41.568063
std        339.262393
min          0.000000
25%          0.000000
50%          3.000000
75%         29.000000
max       9900.000000
Name: ftjuda2_, dtype: float64

In [38]:
data['ftjuda2_'].fillna(math.ceil(data['ftjuda2_'].median()), inplace=True)

### Column 8

In [39]:
data['vegeda2_'].describe()

count    64638.000000
mean       136.077137
std        635.572993
min          0.000000
25%         43.000000
50%         86.000000
75%        100.000000
max       9900.000000
Name: vegeda2_, dtype: float64

In [40]:
data['vegeda2_'].fillna(math.ceil(data['vegeda2_'].median()), inplace=True)

### Column 9

In [41]:
data['grenda1_'].describe()

count    64743.000000
mean        73.972707
std        444.336897
min          0.000000
25%         14.000000
50%         43.000000
75%         71.000000
max       9900.000000
Name: grenda1_, dtype: float64

In [42]:
data['grenda1_'].fillna(math.ceil(data['grenda1_'].median()), inplace=True)

### Column 10

In [43]:
data['x_urbstat'].value_counts()

1.0    55086
2.0     9684
Name: x_urbstat, dtype: int64

In [44]:
data['x_urbstat'].fillna(1, inplace=True)

### Column 11

In [45]:
data['x_metstat'].value_counts()

1.0    44348
2.0    20422
Name: x_metstat, dtype: int64

In [46]:
data['x_metstat'].fillna(1, inplace=True)

### Column 12

In [47]:
data['frnchda_'].describe()

count    64858.000000
mean        26.151022
std        188.733123
min          0.000000
25%          3.000000
50%         14.000000
75%         29.000000
max       9900.000000
Name: frnchda_, dtype: float64

In [48]:
data['frnchda_'].fillna(math.ceil(data['frnchda_'].median()), inplace=True)

### Column 13

In [49]:
data['x_michd'].value_counts()

2.0    59162
1.0     5894
Name: x_michd, dtype: int64

In [50]:
data['x_michd'].fillna(2, inplace=True)

### Column 14


In [51]:
data['x_drdxar3'].value_counts()

2.0    40124
1.0    25264
Name: x_drdxar3, dtype: int64

In [52]:
data['x_drdxar3'].fillna(2, inplace=True)

### Column 15

In [53]:
data['x_lmtwrk3'].value_counts()

3.0    40124
2.0    16270
1.0     8414
9.0      580
Name: x_lmtwrk3, dtype: int64

In [54]:
data['x_lmtwrk3'].fillna(3, inplace=True)

### Column 16

In [55]:
data['x_lmtact3'].value_counts()

3.0    40124
2.0    12709
1.0    12311
9.0      244
Name: x_lmtact3, dtype: int64

In [56]:
data['x_lmtact3'].fillna(3, inplace=True)

### Column 17

In [57]:
data['x_aidtst4'].value_counts()

2.0    38695
1.0    23528
9.0     3578
Name: x_aidtst4, dtype: int64

In [58]:
data['x_aidtst4'].fillna(2, inplace=True)

### Column 18

In [59]:
data['medcost1'].value_counts()

2.0    59244
1.0     6381
7.0      149
9.0       27
Name: medcost1, dtype: int64

In [60]:
data['medcost1'].fillna(2, inplace=True)

### Column 19

In [61]:
data['x_cholch3'].value_counts()

1    55157
3     4455
9     4352
2     1838
Name: x_cholch3, dtype: int64

In [62]:
data['x_cholch3'].fillna(1, inplace=True)

In [63]:
data.to_csv('cleaned_dataset')